### ISSUE TITLE
Okta authentication page remains open

### ISSUE THREAD

**Issue by manuelmmx** [oktadeveloper/okta-openidconnect-appauth-sample-swift#4]
Hello - Wondering if someone can give me a hint of what is going on on my case. I downloaded the app and follow the steps. When I run it, the okta authentication page shows up. After entering the credentials It just remains there. I am expecting a redirect to the app but not happening. If I close the safari view, it looks like I am not authenticated.

Thanks
Manny.

**Comment by jmelberg-okta** [comment]
Hi @manuelmmx,

Sounds like the redirect isn't finding the native app's deep-link. Make sure you set the **redirect URL** in your application's general settings -- and this matches the domain name of the [deep-link](https://github.com/oktadeveloper/okta-openidconnect-appauth-ios#updating-the-ios-deep-link).

For example:
- **redirectURL**: com.example.123456://callback
- **Information Property List**
  - **URL types**
    - **Item 0**
      - **URL Schemes**: com.example.123456

**Comment by manuelmmx** [comment]
Thank you for the quick response.

After a few tries and almost giving up, I found out that, redirectURL was indeed the problem, but not because the redirectURL were different but they had uppercase letters in it. The problem was  when the response was coming back, all letters were lowercase and I was getting a false here:

- (BOOL)shouldHandleURL:(NSURL *)URL {
  NSURL *standardizedURL = [URL standardizedURL];
  NSURL *standardizedRedirectURL = [_request.redirectURL standardizedURL];

  return OIDIsEqualIncludingNil(standardizedURL.scheme, standardizedRedirectURL.scheme) &&
      OIDIsEqualIncludingNil(standardizedURL.user, standardizedRedirectURL.user) &&
      OIDIsEqualIncludingNil(standardizedURL.password, standardizedRedirectURL.password) &&
      OIDIsEqualIncludingNil(standardizedURL.host, standardizedRedirectURL.host) &&
      OIDIsEqualIncludingNil(standardizedURL.port, standardizedRedirectURL.port) &&
      OIDIsEqualIncludingNil(standardizedURL.path, standardizedRedirectURL.path);
}

I hope to finish implementing this on my app with no problem.
