### ISSUE TITLE
Cannot force unwrap value of non-optional type 'Error'

### ISSUE THREAD

**Issue by immontilla** [oktadeveloper/okta-openidconnect-appauth-sample-swift#6]
Hello,

There are 4 compilations errors at ImageViewController.swift:74:90 and OktaAppAuth.swift 305:90, 307:73 and 399:102

I'm using XCode 8.3.3

**Comment by jmelberg-okta** [comment]
@immontilla Thanks for filing this issue and apologies for the late response! We've made integrating AppAuth and Okta easier with the [OktaAppAuth SDK](https://github.com/okta/okta-sdk-appauth-ios). If you're still having trouble, feel free to log an issue there and someone from our team will take a look ASAP.

Thanks!
